package:
  name: pika
  version: "0.10.0"

source:
  fn: pika-0.10.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pika/pika-0.10.0.tar.gz
  md5: db5025bc5abfb0f78573616ee846df31
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pika = pika:main
    #
    # Would create an entry point called pika that calls pika.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pika
    - pika.adapters

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://pika.readthedocs.org 
  license: BSD License
  summary: 'Pika Python AMQP Client Library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
