package:
  name: pytest-twisted
  version: "1.5"

source:
  fn: pytest-twisted-1.5.zip
  url: https://pypi.python.org/packages/source/p/pytest-twisted/pytest-twisted-1.5.zip
  md5: a56ac6c08208f515b681746ab17da96c
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytest-twisted = pytest-twisted:main
    #
    # Would create an entry point called pytest-twisted that calls pytest-twisted.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - greenlet
    - pytest >=2.3
    - decorator

  run:
    - python
    - setuptools
    - greenlet
    - pytest >=2.3
    - decorator

test:
  # Python imports
  imports:
    - pytest_twisted

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/schmir/pytest-twisted
  license: BSD License
  summary: 'A twisted plugin for py.test.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
