package:
  name: mailshake
  version: "0.11.2"

source:
  fn: MailShake-0.11.2.tar.gz
  url: https://pypi.python.org/packages/source/M/MailShake/MailShake-0.11.2.tar.gz
  md5: 3f66702fd86b02a418aa75e9b1698014
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mailshake = mailshake:main
    #
    # Would create an entry point called mailshake that calls mailshake.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - mailshake

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/lucuma/MailShake
  license: MIT License
  summary: 'Dramatically simplify sending email from your python app'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
