package:
  name: txmongo
  version: "15.3.1"

source:
  fn: txmongo-15.3.1.tar.gz
  url: https://pypi.python.org/packages/source/t/txmongo/txmongo-15.3.1.tar.gz
  md5: f5e9b825393b1c501f443ae56de30556
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - txmongo = txmongo:main
    #
    # Would create an entry point called txmongo that calls txmongo.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - twisted >=14.0
    - pymongo >=3.0

  run:
    - python
    - twisted >=14.0
    - pymongo >=3.0

test:
  # Python imports
  imports:
    - txmongo
    - txmongo._gridfs

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/twisted/txmongo
  license: Apache Software License
  summary: 'Asynchronous Python driver for MongoDB <http://www.mongodb.org>'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
