package:
  name: pydispatcher
  version: "2.0.5"

source:
  fn: PyDispatcher-2.0.5.tar.gz
  url: https://pypi.python.org/packages/source/P/PyDispatcher/PyDispatcher-2.0.5.tar.gz
  md5: 1b9c2ca33580c2770577add7130b0b28
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pydispatcher = pydispatcher:main
    #
    # Would create an entry point called pydispatcher that calls pydispatcher.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pydispatch

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pydispatcher.sourceforge.net
  license: BSD License
  summary: 'Multi-producer-multi-consumer signal dispatching mechanism'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
