package:
  name: tldextract
  version: "1.7.1"

source:
  fn: tldextract-1.7.1.tar.gz
  url: https://pypi.python.org/packages/source/t/tldextract/tldextract-1.7.1.tar.gz
  md5: f3273b6865c4be773c36bbb60434a7cd
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tldextract = tldextract:main
    #
    # Would create an entry point called tldextract that calls tldextract.main()

    - tldextract = tldextract.tldextract:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - tldextract
    - tldextract.tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - tldextract --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/john-kurkowski/tldextract
  license: BSD License
  summary: 'Accurately separate the TLD from the registered domain and subdomains of a URL, using the Public Suffix List.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
