package:
  name: mmh3
  version: "2.3.1"

source:
  fn: mmh3-2.3.1.tar.gz
  url: https://pypi.python.org/packages/source/m/mmh3/mmh3-2.3.1.tar.gz
  md5: 388380bfd5f8f702ba2af7e4d72bddee
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mmh3 = mmh3:main
    #
    # Would create an entry point called mmh3 that calls mmh3.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://packages.python.org/mmh3
  license: Public Domain
  summary: 'Python library for MurmurHash (MurmurHash3), a set of fast and robust hash functions.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
