package:
  name: hpack
  version: "1.1.0"

source:
  fn: hpack-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/h/hpack/hpack-1.1.0.tar.gz
  md5: 9928b4285029292db7fa8e16fcbdaa8d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - hpack = hpack:main
    #
    # Would create an entry point called hpack that calls hpack.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - hpack

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://hyper.rtfd.org
  license: MIT License
  summary: 'Pure-Python HPACK header compression'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
