package:
  name: parsel
  version: "1.0.1"

source:
  fn: parsel-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/p/parsel/parsel-1.0.1.tar.gz
  md5: 552f8d7e3267d331134f70c694a2bfb0
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - parsel = parsel:main
    #
    # Would create an entry point called parsel that calls parsel.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - w3lib >=1.8.0
    - lxml
    - six >=1.5.2
    - cssselect >=0.9

  run:
    - python
    - w3lib >=1.8.0
    - lxml
    - six >=1.5.2
    - cssselect >=0.9

test:
  # Python imports
  imports:
    - parsel

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    #- py.test


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - pytest

about:
  home: https://github.com/scrapy/parsel
  license: BSD License
  summary: 'Parsel is a library to extract data from HTML and XML using XPath and CSS selectors'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
