package:
  name: shub
  version: "1.3.4"

source:
  fn: shub-1.3.4.tar.gz
  url: https://pypi.python.org/packages/source/s/shub/shub-1.3.4.tar.gz
  md5: b6aa3a34967d93681bc5c1d5b933cd04
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - shub = shub:main
    #
    # Would create an entry point called shub that calls shub.main()

    - shub = shub.tool:cli

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - click
    - requests
    - six

  run:
    - python
    - click
    - requests
    - six

test:
  # Python imports
  imports:
    - shub

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - shub --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://doc.scrapinghub.com/shub.html
  license: BSD License
  summary: 'Scrapinghub Command Line Client'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
