package:
  name: python-igraph
  version: "0.7.1.post6"

source:
  fn: python-igraph-0.7.1.post6.tar.gz
  url: https://pypi.python.org/packages/source/p/python-igraph/python-igraph-0.7.1.post6.tar.gz
  md5: a4c0b5960735b36adb5d3a40031cb7c0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-igraph = python-igraph:main
    #
    # Would create an entry point called python-igraph that calls python-igraph.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - igraph
    - igraph.app
    - igraph.drawing
    - igraph.remote
    - igraph.test
    - igraph.vendor

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/python-igraph
  license: GNU General Public License (GPL)
  summary: 'High performance graph data structures and algorithms'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
