package:
  name: scikit-image
  version: "0.10.1"

source:
  fn: scikit-image-0.10.1.tar.gz
  url: https://pypi.python.org/packages/source/s/scikit-image/scikit-image-0.10.1.tar.gz
  md5: ee48bdd23933272ee4906980515e8b54

requirements:
  build:
    - python
    - numpy ==1.6.2
    - scipy
    - distribute
    - cython
    - six >=1.3
  run:
    - python
    - numpy ==1.6.2
    - scipy
    - six >=1.3

test:
  imports:
    - skimage

about:
  home: http://scikit-image.org/
  license: Modified BSD (http://scikit-image.org/docs/dev/license.html)
