package:
  name: scrapydo
  version: "0.1.0"

source:
  fn: scrapydo-0.1.0.tar.gz
  url: https://pypi.python.org/packages/source/s/scrapydo/scrapydo-0.1.0.tar.gz
  md5: 246a3ad9fdf91723c34e2009241c14d1
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - scrapydo = scrapydo:main
    #
    # Would create an entry point called scrapydo that calls scrapydo.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - scrapy >=1.0.0
    - crochet >=1.4.0
    - pygments

  run:
    - python
    - scrapy >=1.0.0
    - crochet >=1.4.0
    - pygments

test:
  # Python imports
  imports:
    - scrapydo

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/darkrho/scrapydo
  license: MIT
  summary: 'Crochet-based blocking API for Scrapy.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
