package:
  name: pyasn1-modules
  version: "0.0.6"

source:
  fn: pyasn1-modules-0.0.6.tar.gz
  url: https://pypi.python.org/packages/source/p/pyasn1-modules/pyasn1-modules-0.0.6.tar.gz
  md5: 3b94e7a4999bc7477b76c46c30a56727
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyasn1-modules = pyasn1-modules:main
    #
    # Would create an entry point called pyasn1-modules that calls pyasn1-modules.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - pyasn1 >=0.1.7

  run:
    - python
    - pyasn1 >=0.1.7

test:
  # Python imports
  imports:
    - pyasn1_modules

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://sourceforge.net/projects/pyasn1/
  license: BSD License
  summary: 'A collection of ASN.1-based protocols modules.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
