package:
  name: netlib
  version: "0.13.1"

source:
  fn: netlib-0.13.1.tar.gz
  url: https://pypi.python.org/packages/source/n/netlib/netlib-0.13.1.tar.gz
  md5: fc793a1246b119277c924643c341d841
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - netlib = netlib:main
    #
    # Would create an entry point called netlib that calls netlib.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyasn1 >=0.1.7
    - pyopenssl >=0.15.1
    - cryptography >=0.9
    - passlib >=1.6.2
    - hpack >=1.0.1
    - certifi

  run:
    - python
    - pyasn1 >=0.1.7
    - pyopenssl >=0.15.1
    - cryptography >=0.9
    - passlib >=1.6.2
    - hpack >=1.0.1
    - certifi

test:
  # Python imports
  imports:
    - netlib
    - netlib.http2
    - test
    - test.http2

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/mitmproxy/netlib
  license: MIT License
  summary: 'A collection of network utilities used by pathod and mitmproxy.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
